#!/usr/bin/env python3
"""
Brand Setup Script — creates brand.yaml and optionally renames the skill.

Usage:
    # Create brand.yaml from provided details
    python setup_brand.py --brand-kit brand-kit --name "BrandBrain" \
        --tone "Professional, modern, bold" \
        --primary "#1A1A2E" --secondary "#E94560" --accent "#0F3460" \
        --background "#16213E" --text "#FFFFFF" \
        --style-keywords "minimalist, clean, geometric, tech"

    # Rename the skill after setup
    python setup_brand.py --brand-kit brand-kit --rename-skill
"""

import argparse
import re
import shutil
import sys
from pathlib import Path


def slugify(name):
    """Convert brand name to a clean slug for directory naming."""
    slug = name.lower().strip()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'[\s]+', '-', slug)
    slug = re.sub(r'-+', '-', slug)
    return slug.strip('-')


def create_brand_yaml(args):
    """Create brand.yaml from CLI arguments."""
    brand_kit = Path(args.brand_kit)

    if not brand_kit.exists():
        brand_kit.mkdir(parents=True, exist_ok=True)

    yaml_path = brand_kit / "brand.yaml"

    if yaml_path.exists() and not args.force:
        print("WARNING: brand.yaml already exists at {}".format(yaml_path))
        print("Use --force to overwrite.")
        sys.exit(1)

    # Build YAML content
    lines = []
    lines.append("# {} — Brand Configuration".format(args.name))
    lines.append("# Generated by branded-design setup")
    lines.append("")
    lines.append("# Required fields")
    lines.append('name: "{}"'.format(args.name))
    lines.append('tone: "{}"'.format(args.tone))
    lines.append("colors:")
    lines.append('  primary: "{}"'.format(args.primary))
    lines.append('  secondary: "{}"'.format(args.secondary))
    lines.append('  accent: "{}"'.format(args.accent))
    lines.append('  background: "{}"'.format(args.background))
    lines.append('  text: "{}"'.format(args.text))
    lines.append('style_keywords: "{}"'.format(args.style_keywords))

    # Optional fields
    lines.append("")
    lines.append("# Optional fields")
    if args.tagline:
        lines.append('tagline: "{}"'.format(args.tagline))
    if args.font_heading or args.font_body:
        lines.append("fonts:")
        if args.font_heading:
            lines.append('  heading: "{}"'.format(args.font_heading))
        if args.font_body:
            lines.append('  body: "{}"'.format(args.font_body))
    lines.append('font_strategy: "{}"'.format(args.font_strategy))
    lines.append('logo_placement: "{}"'.format(args.logo_placement))

    yaml_content = "\n".join(lines) + "\n"

    # Write brand.yaml
    yaml_path.write_text(yaml_content)
    print("Created: {}".format(yaml_path))

    # Ensure all subdirectories exist
    subdirs = [
        "logo",
        "fonts",
        "backgrounds",
        "examples/promotional",
        "examples/informational",
        "examples/announcement",
        "examples/engagement",
        "examples/story",
        "photography/products",
        "photography/lifestyle",
        "photography/team",
        "photography/stock",
        "characters/avatars",
        "characters/illustrations",
        "characters/stickers",
        "icons",
        "moodboard",
        "guidelines",
        "feedback-log",
    ]
    for subdir in subdirs:
        (brand_kit / subdir).mkdir(parents=True, exist_ok=True)

    print("")
    print("Brand kit created for: {}".format(args.name))
    print("Location: {}".format(brand_kit.resolve()))
    print("")
    print("Next steps:")
    print("  1. Add your logo to {}/logo/".format(brand_kit))
    print("  2. Add example posts to {}/examples/promotional/".format(brand_kit))
    print("  3. Run: python scripts/validate_brand_kit.py {}".format(brand_kit))


def rename_skill(args):
    """Rename the skill folder and update SKILL.md frontmatter."""
    brand_kit = Path(args.brand_kit)
    yaml_path = brand_kit / "brand.yaml"

    if not yaml_path.exists():
        print("ERROR: brand.yaml not found. Run setup first.")
        sys.exit(1)

    # Parse brand name from brand.yaml
    brand_name = None
    with open(yaml_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('name:'):
                brand_name = line.split(':', 1)[1].strip().strip('"').strip("'")
                break

    if not brand_name:
        print("ERROR: Could not find 'name' in brand.yaml")
        sys.exit(1)

    new_slug = slugify(brand_name) + "-brain"

    # Find the skill root directory (parent of scripts/)
    script_dir = Path(__file__).resolve().parent
    skill_dir = script_dir.parent
    skills_parent = skill_dir.parent  # e.g., ~/.claude/skills/
    new_skill_dir = skills_parent / new_slug

    if new_skill_dir.exists():
        print("ERROR: Directory already exists: {}".format(new_skill_dir))
        sys.exit(1)

    current_name = skill_dir.name
    if current_name == new_slug:
        print("Skill is already named: {}".format(new_slug))
        return

    # Update SKILL.md frontmatter
    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        content = skill_md.read_text()

        # Update name in frontmatter
        content = re.sub(
            r'^name:\s*.*$',
            'name: {}'.format(new_slug),
            content,
            count=1,
            flags=re.MULTILINE
        )

        # Update description to include brand name
        old_desc_pattern = r'(description:\s*)(Generate on-brand social media posts)(.*?)(Use this skill)'
        new_desc = r'\1Generate on-brand social media posts for {}\3\4'.format(brand_name)
        content = re.sub(old_desc_pattern, new_desc, content, count=1, flags=re.DOTALL)

        # Update the title
        content = content.replace(
            "# Brand Post Generator",
            "# {} Post Generator".format(brand_name)
        )

        skill_md.write_text(content)
        print("Updated SKILL.md frontmatter:")
        print("  name: {}".format(new_slug))
        print("  title: {} Post Generator".format(brand_name))

    # Rename the directory
    shutil.move(str(skill_dir), str(new_skill_dir))
    print("")
    print("Skill renamed!")
    print("  From: {}".format(skill_dir))
    print("  To:   {}".format(new_skill_dir))
    print("")
    print("Invoke with: /{}".format(new_slug))


def main():
    parser = argparse.ArgumentParser(description="Brand Post Setup — configure brand kit and rename skill")
    parser.add_argument("--brand-kit", required=True, help="Path to brand-kit directory")

    # Setup mode args
    parser.add_argument("--name", help="Brand name")
    parser.add_argument("--tone", help="Brand tone/personality")
    parser.add_argument("--primary", help="Primary color hex")
    parser.add_argument("--secondary", help="Secondary color hex")
    parser.add_argument("--accent", help="Accent color hex")
    parser.add_argument("--background", help="Background color hex")
    parser.add_argument("--text", help="Text color hex")
    parser.add_argument("--style-keywords", help="Comma-separated style keywords")
    parser.add_argument("--tagline", help="Brand tagline (optional)")
    parser.add_argument("--logo-placement", default="bottom-right",
                        help="Logo placement: bottom-right, bottom-left, top-right, top-left, center")
    parser.add_argument("--font-heading", help="Heading font name (optional)")
    parser.add_argument("--font-body", help="Body font name (optional)")
    parser.add_argument("--font-strategy", default="reference",
                        help="Font strategy: reference or exact")
    parser.add_argument("--force", action="store_true", help="Overwrite existing brand.yaml")

    # Rename mode
    parser.add_argument("--rename-skill", action="store_true",
                        help="Rename skill folder to {brand-name}-brain")

    args = parser.parse_args()

    if args.rename_skill:
        rename_skill(args)
    elif args.name and args.tone and args.primary:
        create_brand_yaml(args)
    else:
        parser.print_help()
        print("\nEither provide brand details (--name, --tone, --primary, etc.) or use --rename-skill")
        sys.exit(1)


if __name__ == "__main__":
    main()
